AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
